# Site settings
title: RCCP II Capacity Development Initiative
email: anelda@talarify.co.za
description: >
  Information about training opportunities offered through RCCP II in 2018.

baseurl: "/rccpii-capdev-2018" # the subpath of your site, e.g. /blog/
url: https://tenet-rccpii.github.io/rccpii-capdev-2018 # the base hostname & protocol for your site
git_address: https://github.com/tenet-rccpii/rccpii-capdev-2018
git_edit_address: https://github.com/tenet-rccpii/rccpii-capdev-2018/blob/gh-pages

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Africa/Johannesburg
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
